export const TABLE_DATA = [
  {
    id: 1,
    name: "Martin Blark",
    address: "Via Monte Bianco 34",
    pinCode: "10100",
    country: "USA",
    state: "California",
    city: "San Francisco",
  },
  {
    id: 2,
    name: "Emily Johnson",
    address: "123 Maple Street",
    pinCode: "94102",
    country: "USA",
    state: "California",
    city: "San Francisco",
  },
  {
    id: 3,
    name: "John Smith",
    address: "456 Oak Avenue",
    pinCode: "90001",
    country: "USA",
    state: "California",
    city: "Los Angeles",
  },
  {
    id: 4,
    name: "Sarah Davis",
    address: "789 Pine Road",
    pinCode: "60614",
    country: "USA",
    state: "Illinois",
    city: "Chicago",
  },
  {
    id: 5,
    name: "Daniel Lee",
    address: "101 Birch Lane",
    pinCode: "30301",
    country: "USA",
    state: "Georgia",
    city: "Atlanta",
  },
  {
    id: 6,
    name: "Rachel Green",
    address: "202 Elm Street",
    pinCode: "10001",
    country: "USA",
    state: "New York",
    city: "New York City",
  },
  {
    id: 7,
    name: "Chris Evans",
    address: "303 Cedar Boulevard",
    pinCode: "94103",
    country: "USA",
    state: "California",
    city: "San Francisco",
  },
  {
    id: 8,
    name: "Amanda White",
    address: "404 Spruce Drive",
    pinCode: "77001",
    country: "USA",
    state: "Texas",
    city: "Houston",
  },
  {
    id: 9,
    name: "James Brown",
    address: "505 Redwood Court",
    pinCode: "33101",
    country: "USA",
    state: "Florida",
    city: "Miami",
  },
  {
    id: 10,
    name: "Lisa Wilson",
    address: "606 Palm Avenue",
    pinCode: "98101",
    country: "USA",
    state: "Washington",
    city: "Seattle",
  },
  {
    id: 11,
    name: "Oliver Harris",
    address: "707 Fir Street",
    pinCode: "85001",
    country: "USA",
    state: "Arizona",
    city: "Phoenix",
  },
  {
    id: 12,
    name: "Sophia Martinez",
    address: "808 Aspen Way",
    pinCode: "72201",
    country: "USA",
    state: "Arkansas",
    city: "Little Rock",
  },
  {
    id: 13,
    name: "Liam Anderson",
    address: "909 Willow Drive",
    pinCode: "48201",
    country: "USA",
    state: "Michigan",
    city: "Detroit",
  },
  {
    id: 14,
    name: "Emma Thomas",
    address: "1010 Maple Lane",
    pinCode: "30302",
    country: "USA",
    state: "Georgia",
    city: "Atlanta",
  },
  {
    id: 15,
    name: "Noah Jackson",
    address: "1111 Oak Street",
    pinCode: "63101",
    country: "USA",
    state: "Missouri",
    city: "St. Louis",
  },
  {
    id: 16,
    name: "Mia Clark",
    address: "1212 Pine Street",
    pinCode: "72202",
    country: "USA",
    state: "Arkansas",
    city: "Little Rock",
  },
  {
    id: 17,
    name: "Benjamin Lewis",
    address: "1313 Cedar Drive",
    pinCode: "85002",
    country: "USA",
    state: "Arizona",
    city: "Phoenix",
  },
  {
    id: 18,
    name: "Charlotte Hall",
    address: "1414 Elm Street",
    pinCode: "10002",
    country: "USA",
    state: "New York",
    city: "New York City",
  },
  {
    id: 19,
    name: "Ethan Young",
    address: "1515 Birch Lane",
    pinCode: "77002",
    country: "USA",
    state: "Texas",
    city: "Houston",
  },
  {
    id: 20,
    name: "Avery King",
    address: "1616 Fir Street",
    pinCode: "94104",
    country: "USA",
    state: "California",
    city: "San Francisco",
  },
  {
    id: 21,
    name: "William Scott",
    address: "1717 Spruce Avenue",
    pinCode: "98102",
    country: "USA",
    state: "Washington",
    city: "Seattle",
  },
  {
    id: 22,
    name: "Emily Johnson",
    address: "123 Maple Street",
    pinCode: "M5A 1A1",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
  },
  {
    id: 23,
    name: "Michael Smith",
    address: "456 Oak Avenue",
    pinCode: "V5K 0A1",
    country: "Canada",
    state: "British Columbia",
    city: "Vancouver",
  },
  {
    id: 24,
    name: "Sarah Brown",
    address: "789 Pine Road",
    pinCode: "H2X 1X1",
    country: "Canada",
    state: "Quebec",
    city: "Montreal",
  },
  {
    id: 25,
    name: "David Lee",
    address: "101 Birch Lane",
    pinCode: "R3A 1A1",
    country: "Canada",
    state: "Manitoba",
    city: "Winnipeg",
  },
  {
    id: 26,
    name: "Olivia White",
    address: "202 Elm Street",
    pinCode: "K1A 0A1",
    country: "Canada",
    state: "Ontario",
    city: "Ottawa",
  },
  {
    id: 27,
    name: "James Harris",
    address: "303 Cedar Boulevard",
    pinCode: "T2P 1A1",
    country: "Canada",
    state: "Alberta",
    city: "Calgary",
  },
  {
    id: 28,
    name: "Emma Clark",
    address: "404 Spruce Drive",
    pinCode: "L6H 0A1",
    country: "Canada",
    state: "Ontario",
    city: "Mississauga",
  },
  {
    id: 29,
    name: "Benjamin Adams",
    address: "505 Redwood Court",
    pinCode: "B3J 1A1",
    country: "Canada",
    state: "Nova Scotia",
    city: "Halifax",
  },
  {
    id: 30,
    name: "Sophia Walker",
    address: "606 Palm Avenue",
    pinCode: "N6A 1A1",
    country: "Canada",
    state: "Ontario",
    city: "London",
  },
  {
    id: 31,
    name: "Lucas King",
    address: "707 Fir Street",
    pinCode: "V6B 2Y8",
    country: "Canada",
    state: "British Columbia",
    city: "Vancouver",
  },
  {
    id: 32,
    name: "Isabella Thompson",
    address: "808 Aspen Way",
    pinCode: "H2J 1Y1",
    country: "Canada",
    state: "Quebec",
    city: "Montreal",
  },
  {
    id: 33,
    name: "Ethan Scott",
    address: "909 Willow Drive",
    pinCode: "S4P 1A1",
    country: "Canada",
    state: "Saskatchewan",
    city: "Regina",
  },
  {
    id: 34,
    name: "Avery Mitchell",
    address: "1010 Maple Lane",
    pinCode: "R2P 1A1",
    country: "Canada",
    state: "Manitoba",
    city: "Winnipeg",
  },
  {
    id: 35,
    name: "Chloe Green",
    address: "1111 Oak Street",
    pinCode: "A1A 1A1",
    country: "Canada",
    state: "Newfoundland and Labrador",
    city: "St. John's",
  },
  {
    id: 36,
    name: "Mason Nelson",
    address: "1212 Pine Street",
    pinCode: "L5B 2Y5",
    country: "Canada",
    state: "Ontario",
    city: "Mississauga",
  },
  {
    id: 37,
    name: "Harper Young",
    address: "1313 Cedar Drive",
    pinCode: "T5J 0A1",
    country: "Canada",
    state: "Alberta",
    city: "Edmonton",
  },
  {
    id: 38,
    name: "Mia Carter",
    address: "1414 Elm Street",
    pinCode: "K7L 1A1",
    country: "Canada",
    state: "Ontario",
    city: "Kingston",
  },
  {
    id: 39,
    name: "Noah Robinson",
    address: "1515 Birch Lane",
    pinCode: "M3A 1A1",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
  },
  {
    id: 40,
    name: "Charlotte Allen",
    address: "1616 Fir Street",
    pinCode: "V5A 1A1",
    country: "Canada",
    state: "British Columbia",
    city: "Burnaby",
  },
  {
    id: 41,
    name: "Liam Harris",
    address: "1717 Spruce Avenue",
    pinCode: "T3K 0A1",
    country: "Canada",
    state: "Alberta",
    city: "Calgary",
  },
  {
    id: 42,
    name: "Jack Wilson",
    address: "123 King Street",
    pinCode: "2000",
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
  },
  {
    id: 43,
    name: "Emily Smith",
    address: "456 Queen Street",
    pinCode: "3000",
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
  },
  {
    id: 44,
    name: "Oliver Brown",
    address: "789 Elizabeth Street",
    pinCode: "4000",
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
  },
  {
    id: 45,
    name: "Sophia Davis",
    address: "101 George Street",
    pinCode: "5000",
    country: "Australia",
    state: "South Australia",
    city: "Adelaide",
  },
  {
    id: 46,
    name: "Liam Johnson",
    address: "202 Collins Street",
    pinCode: "6000",
    country: "Australia",
    state: "Western Australia",
    city: "Perth",
  },
  {
    id: 47,
    name: "Ava White",
    address: "303 Victoria Avenue",
    pinCode: "7000",
    country: "Australia",
    state: "Tasmania",
    city: "Hobart",
  },
  {
    id: 48,
    name: "Noah Jones",
    address: "404 Bourke Street",
    pinCode: "2010",
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
  },
  {
    id: 49,
    name: "Isabella Martinez",
    address: "505 King William Street",
    pinCode: "5210",
    country: "Australia",
    state: "South Australia",
    city: "Adelaide",
  },
  {
    id: 50,
    name: "Lucas Anderson",
    address: "606 Ann Street",
    pinCode: "4001",
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
  },
  {
    id: 51,
    name: "Chloe Thomas",
    address: "707 Hay Street",
    pinCode: "6004",
    country: "Australia",
    state: "Western Australia",
    city: "Perth",
  },
  {
    id: 52,
    name: "Ethan Scott",
    address: "808 Flinders Street",
    pinCode: "3000",
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
  },
  {
    id: 53,
    name: "Charlotte Green",
    address: "909 Eliza Street",
    pinCode: "2000",
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
  },
  {
    id: 54,
    name: "Mason Lee",
    address: "1010 Swanston Street",
    pinCode: "3053",
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
  },
  {
    id: 55,
    name: "Amelia Harris",
    address: "1111 Kent Street",
    pinCode: "2009",
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
  },
  {
    id: 56,
    name: "Aiden Clark",
    address: "1212 George Street",
    pinCode: "2140",
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
  },
  {
    id: 57,
    name: "Ella Walker",
    address: "1313 Albert Street",
    pinCode: "4000",
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
  },
  {
    id: 58,
    name: "Liam Taylor",
    address: "1414 St Georges Terrace",
    pinCode: "6000",
    country: "Australia",
    state: "Western Australia",
    city: "Perth",
  },
  {
    id: 59,
    name: "Grace Robinson",
    address: "1515 Murray Street",
    pinCode: "6000",
    country: "Australia",
    state: "Western Australia",
    city: "Perth",
  },
  {
    id: 60,
    name: "James White",
    address: "1616 Collins Street",
    pinCode: "3000",
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
  },
  {
    id: 61,
    name: "Zoe Young",
    address: "1717 Creek Street",
    pinCode: "4000",
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
  },
  {
    id: 62,
    name: "Benjamin Adams",
    address: "1818 King Street",
    pinCode: "2000",
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
  },
  {
    id: 63,
    name: "Olivia Martin",
    address: "1919 Flinders Lane",
    pinCode: "3000",
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
  },
];

export const TREE_DATA = [
  {
    id: "1",
    value: "USA",
    category: "country",
    children: [
      {
        id: "2",
        value: "California",
        category: "state",
        children: [
          { id: "3", value: "San Francisco", category: "city", children: [] },
          { id: "4", value: "Los Angeles", category: "city", children: [] },
        ],
      },
      {
        id: "5",
        value: "Illinois",
        category: "state",
        children: [
          { id: "6", value: "Chicago", category: "city", children: [] },
        ],
      },
      {
        id: "7",
        value: "Georgia",
        category: "state",
        children: [
          { id: "8", value: "Atlanta", category: "city", children: [] },
        ],
      },
      {
        id: "9",
        value: "New York",
        category: "state",
        children: [
          { id: "10", value: "New York City", category: "city", children: [] },
        ],
      },
      {
        id: "11",
        value: "Texas",
        category: "state",
        children: [
          { id: "12", value: "Houston", category: "city", children: [] },
        ],
      },
      {
        id: "13",
        value: "Florida",
        category: "state",
        children: [
          { id: "14", value: "Miami", category: "city", children: [] },
        ],
      },
      {
        id: "15",
        value: "Washington",
        category: "state",
        children: [
          { id: "16", value: "Seattle", category: "city", children: [] },
        ],
      },
      {
        id: "17",
        value: "Arizona",
        category: "state",
        children: [
          { id: "18", value: "Phoenix", category: "city", children: [] },
        ],
      },
      {
        id: "19",
        value: "Arkansas",
        category: "state",
        children: [
          { id: "20", value: "Little Rock", category: "city", children: [] },
        ],
      },
      {
        id: "21",
        value: "Michigan",
        category: "state",
        children: [
          { id: "22", value: "Detroit", category: "city", children: [] },
        ],
      },
      {
        id: "23",
        value: "Missouri",
        category: "state",
        children: [
          { id: "24", value: "St. Louis", category: "city", children: [] },
        ],
      },
    ],
  },
  {
    id: "25",
    value: "Canada",
    category: "country",
    children: [
      {
        id: "26",
        value: "Ontario",
        category: "state",
        children: [
          { id: "27", value: "Toronto", category: "city", children: [] },
          { id: "28", value: "Ottawa", category: "city", children: [] },
          { id: "29", value: "Mississauga", category: "city", children: [] },
          { id: "30", value: "Kingston", category: "city", children: [] },
        ],
      },
      {
        id: "31",
        value: "British Columbia",
        category: "state",
        children: [
          { id: "32", value: "Vancouver", category: "city", children: [] },
          { id: "33", value: "Burnaby", category: "city", children: [] },
        ],
      },
      {
        id: "34",
        value: "Quebec",
        category: "state",
        children: [
          { id: "35", value: "Montreal", category: "city", children: [] },
        ],
      },
      {
        id: "36",
        value: "Manitoba",
        category: "state",
        children: [
          { id: "37", value: "Winnipeg", category: "city", children: [] },
        ],
      },
      {
        id: "38",
        value: "Nova Scotia",
        category: "state",
        children: [
          { id: "39", value: "Halifax", category: "city", children: [] },
        ],
      },
      {
        id: "40",
        value: "Saskatchewan",
        category: "state",
        children: [
          { id: "41", value: "Regina", category: "city", children: [] },
        ],
      },
      {
        id: "42",
        value: "Newfoundland and Labrador",
        category: "state",
        children: [
          { id: "43", value: "St. John's", category: "city", children: [] },
        ],
      },
      {
        id: "44",
        value: "Alberta",
        category: "state",
        children: [
          { id: "45", value: "Calgary", category: "city", children: [] },
          { id: "46", value: "Edmonton", category: "city", children: [] },
        ],
      },
    ],
  },
  {
    id: "47",
    value: "Australia",
    category: "country",
    children: [
      {
        id: "48",
        value: "New South Wales",
        category: "state",
        children: [
          { id: "49", value: "Sydney", category: "city", children: [] },
        ],
      },
      {
        id: "50",
        value: "Victoria",
        category: "state",
        children: [
          { id: "51", value: "Melbourne", category: "city", children: [] },
        ],
      },
      {
        id: "52",
        value: "Queensland",
        category: "state",
        children: [
          { id: "53", value: "Brisbane", category: "city", children: [] },
        ],
      },
      {
        id: "54",
        value: "South Australia",
        category: "state",
        children: [
          { id: "55", value: "Adelaide", category: "city", children: [] },
        ],
      },
      {
        id: "56",
        value: "Western Australia",
        category: "state",
        children: [
          { id: "57", value: "Perth", category: "city", children: [] },
        ],
      },
      {
        id: "58",
        value: "Tasmania",
        category: "state",
        children: [
          { id: "59", value: "Hobart", category: "city", children: [] },
        ],
      },
    ],
  },
];
